### ISSUE TITLE
NoBackendError  python 3.8 in win 10 x64

### ISSUE THREAD

**Issue by KEHT067** [JPEWdev/pyhid-usb-relay#3]
Hello!
I am have hw-348 usb relay (USB\VID_16C0&PID_05DF&REV_0100)
I am runing example code with python 3.8 in win 10 x64, and answer is:
Traceback (most recent call last):
  File "D:\Desktop\Py\USBHidWatchdog/USB_HID_WATCHDOG.py", line 3, in <module>
    relay = pyhid_usb_relay.find()
  File "D:\Desktop\Py\USBHidWatchdog\lib\site-packages\pyhid_usb_relay\find.py", line 39, in find
    devices = usb.core.find(
  File "D:\Desktop\Py\USBHidWatchdog\lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

But with windows app [usb-relay-hid](https://github.com/pavel-a/usb-relay-hid) relay is working.

Please help me

Thank you

**Comment by KEHT067** [comment]
I fix it bug with libusb dlls 1.0.26 (https://github.com/libusb/libusb) and change hid driver with zadig 2.7 (https://zadig.akeo.ie) to winusb driver.

![Zadig](https://user-images.githubusercontent.com/79023734/163721753-c7a28cbe-7291-4e28-b5f0-b3dcf03816fe.jpg)

libusb-1.0.dll x32 put in Windows/SysWOW64 and libusb-1.0.dll x64 put in Windows/System32 (need VS2015)

But after pyinstaller program not working:
Fix (found on https://github.com/pyinstaller/pyinstaller/issues/1891)

Compilating pyinstaller with .spec file, in .spec file:
binaries = [
   ('C:\\Windows\\System32\\libusb-1.0.dll', '.'),
]

a = Analysis(['myscript.py'],
    ...
    binaries=binaries,
    datas=[],
    hiddenimports=['usb'],  
    ...
